import AdminLayout from 'components/layouts/admin'
import { GetServerSideProps } from 'next'
import Head from 'next/head'
import authenticate from 'utils/middlewares/authenticate'

export const getServerSideProps: GetServerSideProps = async (ctx) => {
    const { req, res } = ctx

    try {
        await authenticate(ctx)
    } catch (error) {
        return {
            redirect: {
                destination: '/login',
                permanent: false,
            },
        }
    }

    return {
        props: {}
    }
}

export default function Page() {

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <AdminLayout>

            </AdminLayout>
        </>
    )
}
