import Head from 'next/head'
import Image from 'next/image'
// import styles from 'styles/Home.module.scss'
import styled, { css } from "styled-components";

const Container = styled.div`
	min-height: 100vh;
	padding: 0 0.5rem;
	display: flex;
	flex-direction: column;
	justify-content: center;
	align-items: center;
	height: 100vh;
`;

const Main = styled.main`
	padding: 5rem 0;
	flex: 1;
	display: flex;
	flex-direction: column;
	justify-content: center;
	align-items: center;
`;

const Title = styled.h1`
	margin: 0;
	line-height: 1.15;
	font-size: 4rem;
	text-align: center;

	&.a {
		color: #0070f3;
  		text-decoration: none;
	}

	&.a:hover,
	&.a:focus,
	&.a:active {
		text-decoration: underline;
	}
`;

const Description = styled.div`
	text-align: center;
	line-height: 1.5;
	font-size: 1.5rem;
`;

const Grid = styled.div`
	display: flex;
	align-items: center;
	justify-content: center;
	flex-wrap: wrap;
	max-width: 800px;
	margin-top: 3rem;

	@media (max-width: 600px) {
		&	{
			width: 100%;
			flex-direction: column;
		}
	}
`;

const Logo = styled.span`
	height: 1em;
	margin-left: 0.5rem;
`;

const Footer = styled.footer`
	width: 100%;
	height: 100px;
	border-top: 1px solid #eaeaea;
	display: flex;
	justify-content: center;
	align-items: center;

	&.a {
		display: flex;
		justify-content: center;
		align-items: center;
		flex-grow: 1;
	}
`;

const Code = styled.code`
	background: #fafafa;
	border-radius: 5px;
	padding: 0.75rem;
	font-size: 1.1rem;
	font-family: Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono, Bitstream Vera Sans Mono, Courier New, monospace;
`;

const Card = styled.a`
	margin: 1rem;
	padding: 1.5rem;
	text-align: left;
	color: inherit;
	text-decoration: none;
	border: 1px solid #eaeaea;
	border-radius: 10px;
	transition: color 0.15s ease, border-color 0.15s ease;
	width: 45%;

	&:hover,
	&:focus,
	&:active {
		color: #0070f3;
		border-color: #0070f3;
	}

	&.h2 {
		margin: 0 0 1rem 0;
		font-size: 1.5rem;
	}

	&.p {
		margin: 0;
		font-size: 1.25rem;
		line-height: 1.5;
	}
`;



export default function Home() {
	return (
		<Container>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Main>
				<Title>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</Title>

				<Description>
					Get started by editing{' '}
					<Code>pages/index.js</Code>
				</Description>

				<Grid>
					<Card href="https://nextjs.org/docs" >
						<h2>Documentation &rarr;</h2>
						<p>Find in-depth information about Next.js features and API.</p>
					</Card>

					<Card href="https://nextjs.org/learn" >
						<h2>Learn &rarr;</h2>
						<p>Learn about Next.js in an interactive course with quizzes!</p>
					</Card>

					<Card
						href="https://github.com/vercel/next.js/tree/master/examples"

					>
						<h2>Examples &rarr;</h2>
						<p>Discover and deploy boilerplate example Next.js projects.</p>
					</Card>

					<Card
						href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"

					>
						<h2>Deploy &rarr;</h2>
						<p>
							Instantly deploy your Next.js site to a public URL with Vercel.
           				 </p>
					</Card>
				</Grid>
			</Main>

			<Footer>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{' '}
					<Logo>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</Logo>
				</a>
			</Footer>
		</Container>
	)
}



// export default function Home() {
// 	return (
// 		<div className={styles.container}>
// 			<Head>
// 				<title>Create Next App</title>
// 				<meta name="description" content="Generated by create next app" />
// 				<link rel="icon" href="/favicon.ico" />
// 			</Head>

// 			<main className={styles.main}>
// 				<h1 className={styles.title}>
// 					Welcome to <a href="https://nextjs.org">Next.js!</a>
// 				</h1>

// 				<p className={styles.description}>
// 					Get started by editing{' '}
// 					<code className={styles.code}>pages/index.js</code>
// 				</p>

// 				<div className={styles.grid}>
// 					<a href="https://nextjs.org/docs" className={styles.card}>
// 						<h2>Documentation &rarr;</h2>
// 						<p>Find in-depth information about Next.js features and API.</p>
// 					</a>

// 					<a href="https://nextjs.org/learn" className={styles.card}>
// 						<h2>Learn &rarr;</h2>
// 						<p>Learn about Next.js in an interactive course with quizzes!</p>
// 					</a>

// 					<a
// 						href="https://github.com/vercel/next.js/tree/master/examples"
// 						className={styles.card}
// 					>
// 						<h2>Examples &rarr;</h2>
// 						<p>Discover and deploy boilerplate example Next.js projects.</p>
// 					</a>

// 					<a
// 						href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
// 						className={styles.card}
// 					>
// 						<h2>Deploy &rarr;</h2>
// 						<p>
// 							Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
// 					</a>
// 				</div>
// 			</main>

// 			<footer className={styles.footer}>
// 				<a
// 					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
// 					target="_blank"
// 					rel="noopener noreferrer"
// 				>
// 					Powered by{' '}
// 					<span className={styles.logo}>
// 						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
// 					</span>
// 				</a>
// 			</footer>
// 		</div>
// 	)
// }
