import Container from 'components/container'
import Head from 'next/head'
import { Button, Grid, Input, Label, Segment } from 'semantic-ui-react'
import { useRouter } from "next/router";
import { GetServerSideProps } from 'next';
import { useState } from 'react';
import useFetch from 'use-http';
import { login } from 'api/auth';

export const getServerSideProps: GetServerSideProps = async (ctx) => {
    const { req, res } = ctx
    const token = req.headers.Authorization

    if (Boolean(token) === true) {
        return {
            redirect: {
                destination: '/contacts',
                permanent: false,
            },
        }
    }

    return {
        props: {}
    }
}

export default function Page() {
    const router = useRouter()
    const { post, response, loading, error } = useFetch(...login())
    const [email, setEmail] = useState<string>('')
    const [password, setPassword] = useState<string>('')

    async function loginHandler() {
        await post("", { email, password })

        router.push('/contacts', undefined, { shallow: true })

    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <Container justifyContent="center" alignItems="center" display="flex">
                <Segment style={{ width: 400 }}>
                    <Grid>
                        <Grid.Row>
                            <Grid.Column width="16">
                                <Label
                                    style={{ marginBottom: 10 }}
                                    content="Email Address"
                                />
                            </Grid.Column>
                            <Grid.Column width="16">
                                <Input
                                    fluid
                                    value={email}
                                    onChange={(event, data) => setEmail(data.value)}
                                />
                            </Grid.Column>
                        </Grid.Row>
                        <Grid.Row>
                            <Grid.Column width="16">
                                <Label
                                    style={{ marginBottom: 10 }}
                                    content="Password"
                                />
                            </Grid.Column>
                            <Grid.Column width="16">
                                <Input
                                    fluid
                                    type="password"
                                    value={password}
                                    onChange={(event, data) => setPassword(data.value)}
                                />
                            </Grid.Column>
                        </Grid.Row>
                        <Grid.Row>
                            <Grid.Column width="16">
                                <Button
                                    disabled={loading}
                                    loading={loading}
                                    fluid
                                    color="green"
                                    content="Iniciar sesion"
                                    onClick={loginHandler}
                                />
                            </Grid.Column>
                        </Grid.Row>
                    </Grid>
                </Segment>
            </Container>
        </>
    )
}
