import AdminTable from 'components/tables'
import Head from 'next/head'
import { Input, Segment } from 'semantic-ui-react'

export default function Page() {

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <Segment>
                <Input
                    iconPosition="left"
                    icon="search"
                    placeholder="Buscar contacto"
                />

                <AdminTable />

                <div style={{ height: 1000 }}></div>
            </Segment>
        </>
    )
}
